obj-y += tempfreq.o temp_distribution.o
ccflags-y += -DDEBUG
obj-$(CONFIG_PHONELAB_TEMPFREQ_AUTOSMP_HOTPLUG_DRIVER) += autosmp.o
obj-$(CONFIG_PHONELAB_TEMPFREQ_MPDECISION_COEXIST) += mpdecision_coexist.o

